default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.3
    hooks:
      - id: typos

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.32.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-format
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs==6.1.1
          - django-guardian
          - django_fsm_log
          - django-unfold
