dist: jammy
language: python
sudo: false
cache: pip

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11

install:
    - pip install tox tox-travis

script:
    - tox --skip-missing-interpreters
