# Generated by Django 6.0.2 on 2026-03-18 12:31
from __future__ import annotations

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    Created from generated one:

    migrations.CreateModel(
        name="StateLog",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ("state_field", models.CharField(max_length=255)),
            (
                "source_state",
                models.CharField(blank=True, default=None, max_length=255, null=True),
            ),
            ("state", models.CharField(max_length=255, verbose_name="Target state")),
            ("transition", models.CharField(max_length=255)),
            ("description", models.TextField(blank=True, null=True)),
            ("object_id", models.TextField()),
            (
                "by",
                models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                ),
            ),
            (
                "content_type",
                models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                ),
            ),
        ],
        options={
            "db_table": "django_fsm_log_statelog",
            "indexes": [
                models.Index(
                    fields=["source_state", "state"], name="django_fsm__source__b87a8b_idx"
                ),
                models.Index(
                    fields=["content_type", "object_id"], name="django_fsm__content_c774a6_idx"
                ),
            ],
        },
    ),
    """

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS "django_fsm_log_statelog" (
                    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "timestamp" datetime NOT NULL,
                    "state_field" varchar(255) NOT NULL,
                    "source_state" varchar(255) NULL,
                    "state" varchar(255) NOT NULL,
                    "transition" varchar(255) NOT NULL,
                    "description" text NULL,
                    "object_id" text NOT NULL,
                    "by_id" integer NULL REFERENCES "auth_user" ("id")
                        DEFERRABLE INITIALLY DEFERRED,
                    "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id")
                        DEFERRABLE INITIALLY DEFERRED);
                CREATE INDEX IF NOT EXISTS "django_fsm_log_statelog_by_id_df6b9a17"
                    ON "django_fsm_log_statelog" ("by_id");
                CREATE INDEX IF NOT EXISTS "django_fsm_log_statelog_content_type_id_e63b15b9"
                    ON "django_fsm_log_statelog" ("content_type_id");
                CREATE INDEX IF NOT EXISTS "django_fsm__source__b87a8b_idx"
                    ON "django_fsm_log_statelog" ("source_state", "state");
                CREATE INDEX IF NOT EXISTS "django_fsm__content_c774a6_idx"
                    ON "django_fsm_log_statelog" ("content_type_id", "object_id");
            """,
            reverse_sql="""
                DROP TABLE "django_fsm_log_statelog";
            """,
        )
    ]
