# Generated by Django 4.2.16 on 2026-01-29 08:32
from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("state_field", models.CharField(max_length=255)),
                (
                    "source_state",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("state", models.CharField(max_length=255, verbose_name="Target state")),
                ("transition", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("object_id", models.TextField()),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_state", "state"], name="django_fsm__source__bb71ee_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"], name="django_fsm__content_9593e3_idx"
                    ),
                ],
            },
        ),
    ]
