name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.14'
          enable-cache: true

      # - name: Install requirements
      #   run: uv sync --dev --frozen

      - name: Run tests
        run: uv run coverage run -m pytest --cov=django_fsm --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
