name: Testing

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Test with python ${{ matrix.python-version }}
      run: uv run -p ${{ matrix.python-version }} tox
